http://localhost:3100/users

###
http://localhost:3100/users/1



###
DELETE  http://localhost:3100/users/618a640f7e7f808f5d6290f4

###
POST http://localhost:3100/users/seed


####################################################
http://localhost:3100/posts


###
DELETE  http://localhost:3100/posts/618cac0f347b76cc068f980e
###

POST http://localhost:3100/posts/search?q=n


###
POST http://localhost:3100/posts/seed

###
http://localhost:3100/exercise

###

POST http://localhost:3100/exercise/seed

###

PATCH http://localhost:3100/users/619d2900c8c789096e0cf178
Content-Type: application/json

{
    "firstName": "Nate"
}